model_id: allenai/OLMoE-1B-7B-0924-Instruct
run_name: olmoe_sciq_linear_k_1_to_topk_full

checkpoint:
  mode: full_adapter
  path: ckpt/olmoe_sciq_linear_k_1_to_topk_full/final_adapter

eval:
  benchmark: sciq
  split: test
  results_dir: eval_results
  run_name: sciq_full_eval

  batch_size: 16
  max_new_tokens: 8
  limit: null

  do_sample: false
  temperature: 0.0

  sort_by_length: true
  compile_model: false
  attn_implementation: sdpa