model_id: openai/gpt-oss-20b
dataset_id: allenai/ai2_arc
dataset_easy_subset: ARC-Easy
dataset_challenge_subset: ARC-Challenge


seed: 42

routing_method: backloaded

use_full: true
full_config:
  r: 16
  full_alpha: 32
  target_modules: all-linear
  full_dropout: 0.05

max_seq_length: 512
max_new_tokens: 8

per_device_train_batch_size: 4
per_device_eval_batch_size: 4
gradient_accumulation_steps: 1

learning_rate: 1.0e-4
optim: adamw_bnb_8bit
lr_scheduler_type: linear
warmup_ratio: 0.03
logging_steps: 10
eval_steps: 100

enable_task_metrics_during_training: false

report_to: wandb
wandb_config:
  project: routing_curriculum
  name: gpt_oss_arc_backloaded_full
  group: gpt_oss_arc

output_dir: ckpt/gpt_oss_arc_backloaded_full
