model_id: microsoft/Phi-mini-MoE-instruct
run_name: phi_sciq_no_curriculum_lora

checkpoint:
  mode: lora_adapter
  path: ckpt/phi_sciq_no_curriculum_lora/final_adapter

eval:
  benchmark: sciq
  split: test
  results_dir: eval_results
  run_name: sciq_lora_eval

  batch_size: 16
  max_new_tokens: 8
  limit: null

  do_sample: false
  temperature: 0.0

  sort_by_length: true
  compile_model: false
  attn_implementation: sdpa
